acer_test:
    resource: "@AcerTestBundle/Controller/"
    type:     annotation
    prefix:   /acer

app:
    resource: '@AppBundle/Controller/'
    type: annotation
blog_show:
    path:      /blog/{slug}
    defaults:  { _controller: AppBundle:Lucky:show ,slug:2333}

blog:
    path:      /blog/{str}
    defaults:  { _controller: AppBundle:Lucky:test ,str:2333}
gao:
    path:      /test
    defaults:  { _controller: GaoBundle:Test:hello}